import type { Metadata } from 'next';

import ThemeProviderClient from '@/site/ThemeProvider';
import { cc } from '@/utility/css';
import { Inter } from 'next/font/google';
import { Nav } from '@/components/Nav';

import '../site/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ThemeProviderClient>
                    <main className={cc('px-3 pb-3', 'lg:px-6 lg:pb-6')}>
                        <Nav />
                        {children}
                    </main>
                </ThemeProviderClient>
            </body>
        </html>
    );
}
