const now = new Date();
export const projects = {
    youngWildFree2: {
        cover: 'youngWildFree2/A_Projectcover.JPG',
        projectDate: new Date('07/01/2021'),
        description: 'A fashion project embracing freedom & youthfulness ',
        files: 'youngWildFree2',
        title: 'Young Wild Free 2',
        displayOrder: 5,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    youngWildFree: {
        cover: 'youngWildFree/A_Projectcover.JPG',
        projectDate: new Date('07/01/2021'),
        description: 'A fashion project embracing freedom & youthfulness ',
        files: 'youngWildFree',
        title: 'Young Wild Free',
        displayOrder: 6,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    yasmine: {
        cover: 'yasmine/A_Projectcover.JPG',
        projectDate: new Date('07/01/2021'),
        description: 'Portfolio work for Yasmine',
        files: 'yasmine',
        title: 'Yasmine',
        displayOrder: 10,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    yas_maima: {
        cover: 'yas_maima/A_Projectcover.JPG',
        projectDate: new Date('02/01/2020'),
        description: 'Yas and Maima 2020',
        files: 'yas_maima',
        title: 'Yas and Maima',
        displayOrder: 11,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    tobi: {
        cover: 'tobi/A_Projectcover.jpg',
        projectDate: new Date('05/08/2019'),
        description: 'Photoshoot with Tobi in Paradise',
        files: 'tobi',
        title: 'Paradise',
        displayOrder: 7,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    tasia: {
        cover: 'tasia/A_Projectcover.JPG',
        projectDate: new Date('09/04/2021'),
        description:
            'Portfolio work for Tasia \n Represented by Good Faces agency',
        files: 'tasia',
        title: 'Tasia',
        displayOrder: 12,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    severeNature: {
        cover: 'severeNature/A_Projectcover.JPG',
        projectDate: new Date('12/30/2021'),
        description: 'Photoshoot for Severe Nature Nigeria',
        files: 'severeNature',
        title: 'Jungle of Africa',
        Category: 'Branded',
        Tag: 'severeNature',
        displayOrder: 1,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    akin: {
        cover: 'portfolioWorkAkin/A_Projectcover.JPG',
        projectDate: new Date('04/17/2019'),
        description: 'Porfolio work for Akin \n Represented by MIM',
        files: 'portfolioWorkAkin',
        title: 'Akin',
        displayOrder: 9,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    onlyFanBTS: {
        cover: 'onlyFanBTS/A_Projectcover.JPG',
        projectDate: new Date('11/16/2021'),
        description:
            'On set of Only fan video shoot featuring Lojay, Zlatan & DJ Neptune',
        files: 'onlyFanBTS',
        title: 'Only Fan (BTS)',
        displayOrder: 8,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    omar: {
        cover: 'omar/A_Projectcover.JPG',
        projectDate: new Date('07/18/2018'),
        description: 'Test shoot with Omar 2018',
        files: 'omar',
        title: 'Omar',
        displayOrder: 18,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    oddminds: {
        cover: 'oddminds/A_Projectcover.JPG',
        projectDate: new Date('07/14/2019'),
        description: 'Work for OddMinds',
        files: 'oddminds',
        title: 'OddMinds',
        Category: 'Branded',
        Tag: 'oddminds',
        displayOrder: 2,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    lojay: {
        cover: 'lojay/A_Projectcover.JPG',
        projectDate: new Date('11/16/2021'),
        description: 'Lojay in London \n Days before his first headline show',
        files: 'lojay',
        title: 'Lojay',
        displayOrder: 8,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    jin: {
        cover: 'jin/A_Projectcover.JPG',
        projectDate: new Date('11/16/2021'),
        description: 'Jinnia, 2019',
        files: 'jin',
        title: 'Jin',
        displayOrder: 14,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    jakeMarcelo: {
        cover: 'jakeMarcelo/A_Projectcover.JPG',
        projectDate: new Date('11/16/2021'),
        description: 'Jake Marcelo for Severe Nature \n London 2021',
        files: 'jakeMarcelo',
        title: 'Jake Marcelo',
        Category: 'Branded',
        Tag: 'Severe Nature',
        displayOrder: 3,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    imen: {
        cover: 'imen/A_Projectcover.JPG',
        projectDate: new Date('07/11/2021'),
        description: 'Portfolio work for Imen \n Agency: GoodFaces',
        files: 'imen',
        title: 'Imen',
        displayOrder: 13,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    gen2care: {
        cover: 'gen2care/A_Projectcover.JPG',
        projectDate: new Date('05/25/2021'),
        description: 'Gen2Care \n Promotional content for Gen2Care ',
        files: 'gen2care',
        title: 'Gen2Care',
        Category: 'Branded',
        Tag: 'company name',
        displayOrder: 4,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    essy_comfort: {
        cover: 'essy_comfort/A_Projectcover.JPG',
        projectDate: new Date('08/26/2019'),
        description: 'Black Queens, 2019',
        files: 'essy_comfort',
        title: 'Essy & Comfort',
        displayOrder: 16,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    dija: {
        cover: 'dija/A_Projectcover.JPG',
        projectDate: new Date('10/26/2019'),
        description: 'Pink Fall with Dija, 2019',
        files: 'dija',
        title: 'Dija',
        displayOrder: 17,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    anthony: {
        cover: 'anthony/A_Projectcover.JPG',
        projectDate: new Date('11/16/2021'),
        description: 'Monochrome with Anthony \n London 2021',
        files: 'anthony',
        title: 'Anthony',
        displayOrder: 14,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
    alaa: {
        cover: 'alaa/A_Projectcover.JPG',
        projectDate: new Date('10/26/2019'),
        description: 'Pink Illusion',
        files: 'alaa',
        title: 'Alaa',
        displayOrder: 15,
        isPublished: false,
        additionalInfo: {
            Editor: 'Franky Frank',
            'Special Effects': 'Bobby Bob',
            'Costume Design': 'Robbby Rob',
            'Sound Artist': 'Johnny Jon',
            'Lighting': 'Sammy Sam',
            Models: 'Jane, Jamie, Janet, Jack, Jim',
        },
    },
};
